name: Linux Package

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build-and-package:
    uses: ./.github/workflows/build.yml
    with:
      os: ubuntu-24.04
      platform: linux-x86_64
      package: true
